Vagrant.configure(2) do |config|
  config.vm.box = "draducanu/idea"

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provider "virtualbox" do |vb|
   vb.memory = "4024"
   vb.cpus = 2
  end

  config.vm.synced_folder "./", "/home/vagrant/IdeaProjects"
  config.vm.network "public_network"

  config.vm.provision "shell", inline: "~/resources/install.sh", privileged: false
end

#linux: sudo vagrant ssh -c '~/idea.sh settings.git'
#windows: sudo vagrant ssh -c 'export DISPLAY='aaaa:0.0' && ~/idea.sh settings.git'
#####.\Xming.exe  -clipboard -multiwindow -ac

